### PR TITLE
#22 avoid repetitive call $this->_calculatePageCount() in count() method if count equals zero

### PR DESCRIPTION
**Pull request by fedys**
#22

### CODE REVIEW

**Comment by froschdesign** [comment]
Duplicates #25

**Comment by fedys** [comment]
@froschdesign you are right my PR is duplicating #25 but my PR contains tests which tests the repetitive call of `Zend\Paginator\Paginator::_calculatePageCount()` unlike the PR #25. Please consider merging of my `ZendTest\Paginator\PaginatorTest::testRepetitiveCallCountResultingZeroDoesNotCauseRepetitiveCallOfCalculatePageCountMethod()`

**Comment by froschdesign** [comment]
I've seen it and I prefer your test in this special case.

**Comment by fedys** [comment]
thanks :)

**Comment by froschdesign** [comment]
@fedys 
Can you simplify the test method name? Maybe replace "RepetitiveCallCountResultingZero" with "CountResultOfZero" or something shorter.

**Comment by weierophinney** [comment]
> Can you simplify the test method name?

Just a note: as a general rule, the more descriptive the name, the better. Test names should indicate the _behavior_ being tested.

**Comment by weierophinney** [comment]
Thanks, @fedys!

**Pull request merged**
