### PR TITLE
Travis CI hotfix & Updated to php-coveralls/php-coveralls

### PR DESCRIPTION
**Pull request by michalbundyra**
With version 2 package has been renamed from `satooshi/php-coveralls` to `php-coveralls/php-coveralls`, and the script has been renamed from `coveralls` to `php-coveralls`

### CODE REVIEW

**Comment by michalbundyra** [comment]
Updated Travis CI configuration - fixed env variables, these are case sensitive.
Now tests failing on PHP 7.2 lowest and locked because of zend-db. Should we update the minimum requirements to ^2.9? Then all should be fine.

**Comment by weierophinney** [comment]
> Should we update the minimum requirements to ^2.9? Then all should be fine.

Yes.

**Comment by michalbundyra** [comment]
@weierophinney It's updated now

**Comment by weierophinney** [comment]
Thanks, @webimpress

**Pull request merged**
